name: Stupidiots — Cancel Stuck Workflow Runs

on:
  schedule:
    - cron: '*/1 * * * *' # every minute
  workflow_dispatch:

jobs:
  cancel:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    timeout-minutes: 10
    concurrency:
      group: cancel-stuck-runs
      cancel-in-progress: true
    steps:
      - name: Cancel in-progress runs older than 30 minutes
        uses: actions/github-script@v7
        with:
          script: |
            const cutoffMinutes = 5;
            const { owner, repo } = context.repo;
            const now = new Date();
            const runs = await github.paginate(github.rest.actions.listWorkflowRunsForRepo, {
              owner,
              repo,
              per_page: 100,
              status: 'in_progress'
            });
            for (const run of runs) {
              const started = new Date(run.created_at);
              const ageMin = (now - started) / 60000;
              if (ageMin > cutoffMinutes) {
                core.info(`Cancelling stuck run ${run.id} (${run.name}) age=${ageMin.toFixed(1)}m`);
                await github.rest.actions.cancelWorkflowRun({ owner, repo, run_id: run.id });
              }
            }

