name: Commit Proxy

on:
  workflow_dispatch:
    inputs:
      filename:
        description: "File path to create or update"
        required: true
        default: "PROGRESS.md"
      message:
        description: "Commit message"
        required: true
        default: "auto-update via Commit Proxy"
      content:
        description: "Base64-encoded file content"
        required: true

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Perform authenticated commit
        env:
          GH_TOKEN: ${{ secrets.idiot-personal-access }}
          REPO: ${{ github.repository }}
          FILE: ${{ github.event.inputs.filename }}
          MESSAGE: ${{ github.event.inputs.message }}
          CONTENT: ${{ github.event.inputs.content }}
        run: |
          curl -s -X PUT \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$REPO/contents/$FILE \
            -d "{\"message\":\"$MESSAGE\",\"content\":\"$CONTENT\"}"
