name: Stupidiots — Delete Failed Workflow Runs

on:
  schedule:
    - cron: '*/5 * * * *' # every 5 minutes
  workflow_dispatch:

jobs:
  delete_failed:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    timeout-minutes: 10
    concurrency:
      group: delete-failed-runs
      cancel-in-progress: true
    steps:
      - name: Delete failed runs older than 10 minutes
        uses: actions/github-script@v7
        with:
          script: |
            const cutoffMinutes = 10;
            const { owner, repo } = context.repo;
            const now = new Date();
            const runs = await github.paginate(github.rest.actions.listWorkflowRunsForRepo, {
              owner,
              repo,
              per_page: 100,
              status: 'failure'
            });
            let deleted = 0;
            for (const run of runs) {
              const created = new Date(run.created_at);
              const ageMin = (now - created) / 60000;
              if (ageMin > cutoffMinutes) {
                core.info(`Deleting failed run ${run.id} (${run.name}) age=${ageMin.toFixed(1)}m`);
                await github.rest.actions.deleteWorkflowRun({ owner, repo, run_id: run.id });
                deleted++;
              }
            }
            core.info(`Deleted ${deleted} failed runs`);

