name: Deploy Website to Hostinger

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Prepare website files
      run: |
        echo "Preparing website files for Hostinger deployment..."
        # Copy public_html files to dist directory
        mkdir -p dist
        cp -r public_html/* dist/
        echo "Website files prepared successfully"
        
    - name: Deploy to Hostinger
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.HOSTINGER_FTP_HOST }}
        username: ${{ secrets.HOSTINGER_FTP_USER }}
        password: ${{ secrets.HOSTINGER_FTP_PASS }}
        local-dir: ./dist/
        server-dir: /public_html/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.env
          **/.env.*
          **/contracts/**
          **/artifacts/**
          **/cache/**
          **/scripts/**
          **/test/**
          **/hardhat.config.*
          **/package.json
          **/package-lock.json
