name: Deploy to Staging

on:
  push:
    branches: [ staging ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      REMOTE_DIR: /var/www/staging
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install rsync and ssh-client
        run: sudo apt-get update && sudo apt-get install -y rsync openssh-client

      - name: Start ssh-agent and add private key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts

      - name: Validate inputs
        run: |
          test -n "$SSH_USER" && test -n "$SSH_HOST"
          test -d public_html

      - name: Rsync public_html to staging
        run: |
          rsync -az --delete public_html/ "$SSH_USER@$SSH_HOST:$REMOTE_DIR/"

      - name: Reload Nginx
        run: |
          ssh "$SSH_USER@$SSH_HOST" 'nginx -t || sudo nginx -t'
          ssh "$SSH_USER@$SSH_HOST" 'systemctl reload nginx || sudo systemctl reload nginx'
